# Agenda

**Tópicos**:
* Numpy:
 - Indexação
 - Manipulação de Arrays:
    - vstack/hstack
    - concatenate
    - append
  - Funções Matemáticas
    - Trigonométricas
    - Aritméticas
    - Outras funções importantes
  - Operações entre arrays


In [2]:
import numpy as np

## Indexação

*  É possível indexar um array usando índices inteiros
*  Usando uma lista de booleanos
*  Usando lista de inteiros

In [3]:
a = np.array( [1, 2, 3] )
b = np.array( [[2, 3, 4], [5, 6, 7]] )

In [4]:
print(b)

[[2 3 4]
 [5 6 7]]


In [5]:
print(a[0])
print(b[0, 1])
print(b[1, 2])

1
3
7


In [6]:
3 > 1

True

Na aula passada fizemos operações aritméticas em um array, e se fizéssemos lógicas? Exemplo `a > 1` ?

In [7]:
print(a>1)

[False  True  True]


E se eu fizer a mesma coisa com b?

In [8]:
print(b > 3)

[[False False  True]
 [ True  True  True]]


In [9]:
a[a == 1]

array([1])

In [10]:
np.mean(a)

2.0

In [11]:
a[ a < (np.mean(a) - 2*np.std(a)) ]

array([], dtype=int32)

In [12]:
np.where(a > 1)

(array([1, 2], dtype=int64),)

In [13]:
a[np.where(a > 1)]

array([2, 3])

In [14]:
a.shape

(3,)

In [15]:
np.where(b > 3)

(array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [16]:
b[ np.where(b > 3) ]

array([4, 5, 6, 7])

In [17]:
b > 3

array([[False, False,  True],
       [ True,  True,  True]])

In [18]:
b[b > 3]

array([4, 5, 6, 7])

In [19]:
b[0,0] = 200

In [20]:
print(b)

[[200   3   4]
 [  5   6   7]]


## Manipulação de Arrays

### hstack/vstack

In [21]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
c = np.array([1, 1, 1])
print(np.vstack((c,a,b)))

[[1 1 1]
 [1 2 3]
 [2 3 4]]


In [22]:
c = np.vstack((a,b))

In [23]:
print(c)

[[1 2 3]
 [2 3 4]]


In [24]:
type(c)

numpy.ndarray

**Observações**: 
- Recebe uma tupla como entrada
- Arrays podem ter mais de uma dimensão
- Retorna uma variável nova

In [25]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [26]:
print(a)
print(b)

[1 2 3]
[2 3 4]


In [31]:
a = np.array([[7],[5],[8]])
b = np.array([[2],[3],[4]])
xuxu = np.hstack((a,b))
print(xuxu)

[[7 2]
 [5 3]
 [8 4]]


### append

In [44]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.append(a, b) 

array([1, 2, 3, 2, 3, 4])

In [45]:
a = np.array( [[1,2,3], [4,5,6]] )
b = np.array([2,3,4])
np.append(a, b) 

array([1, 2, 3, 4, 5, 6, 2, 3, 4])

In [47]:
a = np.array( [[1,2,3], [4,5,6]] )



In [48]:
b = np.array([2,3,4]).reshape(1, 3)

In [51]:
print(a,b)

[[1 2 3]
 [4 5 6]] [[2 3 4]]


In [53]:
np.append(a, b, axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4]])

In [40]:
b = np.array([2,3,4])

In [54]:
print(b)

[[2 3 4]]


In [55]:
b.shape

(1, 3)

In [56]:
b.ndim

2

In [79]:
a = np.array([[1,2,3,7], [4,5,6,4],[4,5,6,4]] )
b = np.array([[2,3,4,6], [1,1,1,4],[1,1,1,4]])
c = np.array([[2,3,4,6], [1,1,1,4],[1,1,1,4]])

In [83]:
np.append(a, b,  axis=0)


array([[1, 2, 3, 7],
       [4, 5, 6, 4],
       [4, 5, 6, 4],
       [2, 3, 4, 6],
       [1, 1, 1, 4],
       [1, 1, 1, 4]])

### Concatenação Arrays

Podemos unir 2 ou mais arrays, lateralmente ou verticalmente.

In [84]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
array2D_1 = array.reshape((3,3))
array2D_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [86]:
array2D_2 = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18]).reshape((3,3))

In [87]:
print(array2D_2)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [88]:
# concatenação vertical
np.concatenate((array2D_1, array2D_2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [97]:
# concatenação horizontal
np.concatenate((array2D_1,array2D_2),axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15],
       [ 6,  7,  8, 16, 17, 18]])

In [98]:
# E como concatenar mais de 2 arrays
np.concatenate((array2D_1, array2D_2, array2D_1, array2D_1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [99]:

array2D_1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [105]:
np.concatenate((array2D_1, np.arange(4).reshape(4,4)))

ValueError: cannot reshape array of size 4 into shape (4,4)

## Funções Matemáticas

O Numpy possui algumas funções e submódulos que auxiliam o dia a dia do cientista.

In [106]:
# Média
np.mean( [1,2,3,4] )

2.5

In [107]:
np.sum([1,2,3,4] )

10

In [108]:
# Desvio Padrão
np.std([1,2,3,4])

1.118033988749895

In [109]:
#mediana
np.median([1,2,3,4])

2.5

In [110]:
print(array2D_1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [111]:
np.mean( array2D_1, axis=1 )

array([1., 4., 7.])

As funções acima aceitam axis

O np.arange cria um vetor espaçado entre dois números.

In [112]:
# np.arange
x = np.arange(start=1, stop=20, step=2) #as 3 opçoes do arange

In [113]:
np.arange(5, 10, 0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [114]:
print(x)

[ 1  3  5  7  9 11 13 15 17 19]


In [115]:
np.random.shuffle(x)
print(x)

[ 5 19 15  9  7 13 11 17  3  1]


np.linspace gera um array de n números entre dois valores.

In [116]:
# np.linspace
np.linspace(start=1, stop=10, num=50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [117]:
# np.where 
x = np.arange(9).reshape(3, 3)
x


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [118]:
np.where( x > 2 )

(array([1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [119]:
x[np.where( x%2 == 0 )]

array([0, 2, 4, 6, 8])

O submódulo random do numpy pode ser utilizado para gerar números aleatórios, selecionar e embaralhar números.

In [120]:
# escolha aleatória
np.random.choice([1,2,3,4,5], 3, replace=False)

array([3, 1, 4])

In [121]:
# embaralhamento
x = [1,2,3]
np.random.shuffle(x)

In [122]:
x

[1, 2, 3]

## Operaçõe entre Arrays

In [141]:
start = time.time() 
array1 = np.arange(9)
array2 = np.arange(9)

In [124]:
print(array1)
print(array2)

[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]


In [125]:
# Soma
print(array1 + array2)

[ 0  2  4  6  8 10 12 14 16]


In [126]:
# Subtração
array1 - array2

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [127]:
# Divisão
array1/array2

C:\Users\lucas\AppData\Local\Temp/ipykernel_3144/1676965899.py:2: RuntimeWarning: invalid value encountered in true_divide
  array1/array2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [128]:
# Multiplicação
array1*array2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

E se tentarmos fazer operações com listas???

In [129]:
[1,2,3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [133]:
[1,2,3]*[4, 5, 6]

TypeError: can't multiply sequence by non-int of type 'list'

In [131]:
[1,2,3]/[4, 5, 6]

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [132]:
[1,2,3]-[4, 5, 6]

TypeError: unsupported operand type(s) for -: 'list' and 'list'

# Medir o tempo de execução

In [134]:
import time

In [135]:
start = time.time()
# codigo a ser mensurado
end = time.time()
print(end - start)

0.0


In [136]:
size_of_vec = 100

# python list
start = time.time() 

X = range(size_of_vec)
Y = range(size_of_vec)
Z = [X[i] + Y[i] for i in range(len(X)) ]

end = time.time()
print(end - start)

0.0010063648223876953


In [137]:
#numpy
start = time.time() 

X = np.arange(size_of_vec)
Y = np.arange(size_of_vec)
Z = X + Y

end = time.time()
print(end - start)

0.0


In [140]:
%%time

X = np.arange(size_of_vec)
Y = np.arange(size_of_vec)
Z = X + Y

Wall time: 0 ns
