In [1]:
import numpy as np

In [ ]:
#Ex1: Substitua todos os números ímpares em arr por -1 sem alterar arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


#output desejado:
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Ex2: Empilhe as  matrizes a e b verticalmente
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)


#output desejado:
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

In [ ]:
#Ex3: Extraia os itens em comum entre a e b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#output desejado:
#array([2, 4])

In [ ]:
#Ex4: Imprima ou mostre apenas 3 casas decimais da matriz numpy rand_arr
rand_arr = np.random.random((5,3))


In [ ]:
#Ex5: Importando um conjunto de dados com números e textos mantendo o texto intacto em python numpy:

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [ ]:
#Ex6: Imprima as 3 primeiras linhas de iris

In [ ]:
#Ex7: Encontre a media, mediana e desvio padrao da coluna sepallength do dataset iris (primeira coluna)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [ ]:
#Ex8 Encontre o 5o e o  95o percentil da coluna sepallength do dataset iris
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])